### PR TITLE
Fix modman mapping.

### PR DESCRIPTION
**Pull request by johnnywidth**
Fix modman mapping. Exclude all shell directory from .gitignore, only module's files.

### CODE REVIEW

**Comment by robbieaverill** [comment]
@johnnywidth - is there an issue with the original?

**Comment by johnnywidth** [comment]
@robbieaverill Original is writing to .gitignore full shell directory. This fix is writing only shell/ecomdev-phpunit.php. It's critical, because people may have there own scripts in shell, and there are covering by gitignore.

**Comment by robbieaverill** [comment]
+1

On Wednesday, 18 November 2015, Oleksandr Mosur <notifications@github.com>
wrote:

> @robbieaverill <https://github.com/robbieaverill> Original is writing to
> .gitignore full shell directory. This fix is writing only
> shell/ecomdev-phpunit.php. It's critical, because people may have there own
> scripts in shell, and there are covering by gitignore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EcomDev/EcomDev_PHPUnit/pull/260#issuecomment-157642345>
> .
>


-- 
*Robbie Averill*
LA PETITE MANOUCHE - NZ Gypsy Jazz Guitar Duo
Phone: +64 27 321 4758
contact@lapetitemanouche.com
www.lapetitemanouche.com

**Comment by IvanChepurnyi** [comment]
I don't think that this is an extension problem, more an issue in composer-installer that puts into git ignore files that are outside of extension.

**Comment by johnnywidth** [comment]
@IvanChepurnyi Nope. In modman config file you say about mapping, which files would be written to gitignore. it's not composer deal at all.

**Comment by IvanChepurnyi** [comment]
Yes the modman file tells about the mapping, and having * (wildcard) as a mapping an absolutely correct way to sepcify it. Please refer to modman documentation for explanation. 

Gitingore is generated by custom written composer install script, that you all seems refering too.
When I use `"magento-hackathon/magento-composer-installer": "~3.0"` as a dependency such files are placed into my .gitignore:

```
/app/etc/modules/EcomDev_PHPUnit.xml
/app/etc/modules/EcomDev_PHPUnitTest.xml
/app/code/community/EcomDev/PHPUnit
/app/code/community/EcomDev/PHPUnitTest
/lib/EcomDev/PHPUnit
/lib/EcomDev/Utils
/lib/Spyc
/lib/vfsStream
/shell/ecomdev-phpunit.php
```
As you see no wildcards, and it is working correctly. That is why issue is not in extension, issue is in your deployment tool, as you probably use a different composer installer.

**Pull request closed without merging**
